
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["sophisticatedbackpacks:void_upgrade|true", "sophisticatedbackpacks:diamond_backpack|true", "sophisticatedbackpacks:gold_backpack|true", "sophisticatedbackpacks:inception_upgrade|true"]

