[Spawning]
	#━━━━━━━━━━
	#A global factor that determines if a spawn attempt for a trainer is made.
	#Range: 0.0 ~ 1.0
	globalSpawnChance = 0.85
	#━━━━━━━━━━
	#The chance for a trainer to spawn will shrink towards this value based of how many
	#trainers are already spawned in for a player. For example if a player has 0 trainers
	#spawned for them the chance will be as configured by globalSpawnChance, if a player
	#has barely filled up their spawn cap (maxTrainersPerPlayer), i.e. only one more free
	#spot is left, the chance for the last trainer will be as configured by globalSpawnChanceMinimum.
	#Set to any value equal to or above globalSpawnChance to disable (e.g. 1.0).
	#Range: 0.0 ~ 1.0
	globalSpawnChanceMinimum = 0.15
	#━━━━━━━━━━
	#The interval in ticks at which a spawn attempt is made per player.
	#Range: 1 ~ 2147483646
	spawnIntervalTicks = 120
	#━━━━━━━━━━
	#The spawn interval ticks will grow towards this value based of how many trainers are already
	#spawned in for a player. For example if a player has 0 trainers spawned for them the spawn
	#interval ticks will be as configured by spawnIntervalTicks, if a player has barely filled up their
	#spawn cap (maxTrainersPerPlayer), i.e. only one more free spot is left, the spawn interval for the
	#last trainer will be as configured by spawnIntervalTicksMaximum. Set to any value equal to or below
	#spawnIntervalTicks to disable (e.g. 0).
	#Range: 0 ~ 2147483646
	spawnIntervalTicksMaximum = 1200
	#━━━━━━━━━━
	#The max horizontal distance a trainer can spawn from players.
	#Range: 1 ~ 2147483646
	maxHorizontalDistanceToPlayers = 70
	#━━━━━━━━━━
	#The min horizontal distance a trainer can spawn from players.
	#Range: 1 ~ 2147483646
	minHorizontalDistanceToPlayers = 25
	#━━━━━━━━━━
	#The max vertical distance a trainer can spawn from players.
	#Range: 1 ~ 2147483646
	maxVerticalDistanceToPlayers = 30
	#━━━━━━━━━━
	#Spawn cap of trainers per player.
	#Range: 0 ~ 2147483646
	maxTrainersPerPlayer = 12
	#━━━━━━━━━━
	#Total trainer spawn cap. This value may be increased for servers with higher expected
	#player numbers (> 4), for example (|players| + 1)*maxTrainersPerPlayer.
	#Range: 0 ~ 2147483646
	maxTrainersTotal = 60
	#━━━━━━━━━━
	#The maximum level difference between the strongest pokemon in the team of a player and the strongest
	#pokemon in the team of a trainer to spawn for that player. The spawn weight decreases with a higher
	#level difference. Trainers with pokemon above the level cap of a player are excluded.
	#Range: 0 ~ 100
	maxLevelDiff = 25
	#━━━━━━━━━━
	#If enabled trainers will only spawn naturally around players that have a trainer card
	#in their inventory (does not affect trainer spawners).
	spawningRequiresTrainerCard = false
	#━━━━━━━━━━
	#If enabled a single trainer association npc may spawn naturally nearby players that carry a trainer
	#card and have either not started a series or completed their current series. One may also spawn nearby
	#any player in proximity to a village (at least 3 occupied beds and a village center). These can
	#spawn everywhere but will respect the 'dimensionBlacklist' and 'dimensionWhitelist' settings.
	spawnTrainerAssociation = true
	#━━━━━━━━━━
	#A comma separated list of dimensions (e.g. ["multiworld:spawn", "minecraft:the_end"]).
	#In these dimensions trainers will never spawn.
	dimensionBlacklist = []
	#━━━━━━━━━━
	#A comma separated list of dimensions (e.g. ["multiworld:spawn" , "minecraft:the_end"]).
	#Trainers may only spawn in these dimensions (unless the list is empty).
	dimensionWhitelist = []
	#━━━━━━━━━━
	#A comma separated list of biome tags (e.g. ["is_overworld", "is_forest"]).
	#A biome may not have any of the given tags attached to it, for a trainer to spawn in that biome.
	#Trainers may also have additional tags defined by a data pack.
	biomeTagBlacklist = []
	#━━━━━━━━━━
	#A comma separated list of biome tags (e.g. ["is_overworld", "is_forest"]).
	#A biome must have atleast one of the given tags attached to it, for a trainer to spawn in that
	#biome (unless the list is empty). Trainers may also have additional tags defined by a data pack.
	biomeTagWhitelist = []

[Players]
	#━━━━━━━━━━
	#Initial level cap of players. Pokemon will not gain any experience if at or above the level cap.
	#Range: 1 ~ 100
	initialLevelCap = 15
	#━━━━━━━━━━
	#The required level cap for trainers is based of the strongest pokemon in their team.
	#This value will be added to the derived player level cap (including the initial level cap).
	#Example: A trainer with a Pikachu at level 50 has a level cap requirement of 50.
	#If the additiveLevelCapRequirement is -10 the required level cap for that trainer becomes 40,
	#if it is 10 the level cap requirement becomes 60.
	additiveLevelCapRequirement = 0
	#━━━━━━━━━━
	#If enabled the level cap of a players will not prevent their pokemon from gaining experience and leveling up.
	#Trainers will still refuse to battle players that carry pokemon above their level cap!
	allowOverLeveling = false
	#━━━━━━━━━━
	#The initial series players are placed in when entering a world for the first time. Apart from any series id
	#this value may also be set to one of the special series ids "empty" (i.e. no series) or "freeroam".
	#Note that when setting the initial series to "freeroam" it is usually a good idea to also disable
	#'freeroamRequiresCompletedSeries'.
	initialSeries = "empty"
	#━━━━━━━━━━
	#The freeroam series will grant a level cap of 100 and allows players to pause the progression of their
	#current series. If this option is enabled, players must have completed any other series first to gain
	#access to the trade at the trainer association.
	freeroamRequiresCompletedSeries = true

[Debug]
	#━━━━━━━━━━
	#If enabled additional information are printed to the log whenever a trainer spawns or despawns.
	logSpawning = false
